#!/usr/bin/env groovy
def SERVER_URL = "http://jfrog.local/artifactory"

node {
    stage('Configure helm & add Artifactory repo') {
        /* Configure helm client to point to k8s cluster */
         withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: CREDENTIALS, usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
           sh "sudo helm repo add rt-helm-virtual ${SERVER_URL}/helm-virtual --username ${env.USERNAME} --password ${env.PASSWORD}"
           sh "sudo helm repo update"
         }
    }

    stage('Deploy chart pulling from Artifactory') {
        /* Finally, we'll deploy the image to k8s using helm chart. */
        sh "sudo helm upgrade my-docker-go-app --install --recreate-pods rt-helm-virtual/docker-go-app-chart"
    }
}
